---
# tasks file for python_pip
- name: install python pip
  package:
    name: "{{ python_pip_packages }}"
    state: present
  register: python_pip_install_python_pip
  until: python_pip_install_python_pip is succeeded
  retries: 3

- name: update pip
  pip:
    name: pip
    state: latest
  register: python_pip_update_pip
  until: python_pip_update_pip is succeeded
  retries: 3

- name: configure pip proxy
  ini_file:
    path: /etc/pip.conf
    section: global
    option: index-url
    value: "{{ python_pip_proxy }}"
  when:
    - python_pip_proxy is defined

- name: trust hosts
  ini_file:
    path: /etc/pip.conf
    section: global
    option: trusted-host
    value: "{{ python_pip_trusted_host }}"
  when:
    - python_pip_trusted_host is defined

- name: install requested modules
  pip:
    name: "{{ item.name }}"
    state: present
    version: "{{ item.version | default(omit) }}"
  loop: "{{ python_pip_modules }}"
  loop_control:
    label: "{{ item.name }}"
  register: install_requested_modules
  until: install_requested_modules is succeeded
  retries: 3
